config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'application#index'

  # get 'list', action: :show, to: 'list'

  resources :lists
  resources :projects, only: %w[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_one :user
  has_many :list_entries
end

app/models/list_entry.rb
class ListEntry < ApplicationRecord
  belongs_to :list

  attr_accessor :text
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate_user!
    if current_user.nil?
      redirect_to '/'
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @wat = 'naw'
  end

  def show
    render json: { msg: 'wwat' }, status: 200
  end

  def user_lists
    List.where(user: current_user)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = current_user.projects
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/application/bob.html.erb
<div>{ 'bob was here' }</div>

app/views/application/index.html.erb
<%= link_to 'Projects', projects_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecklessRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag    'application' %>
  </head>

  <body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>

  <%= react_component('Header', { greeting: "Reckless Rails" }) %>
  <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div>
  <%= react_component('lists/ListTable', { lists: user_lists }) %>
</div>

app/views/projects/_project.html.erb
<p>
  <%= "Name: #{project.name}" %>
</p>

app/views/projects/_projects.html.erb
<%= render partial: 'project' , collection: projects  %>

app/views/projects/index.html.erb
<h1>Projects#index</h1>

<div>
  <%= render partial: 'projects' , locals: { projects: @projects } %>
</div>

app/views/projects/show.html.erb
<h1>Projects#show</h1>
<p>Find me in app/views/projects/show.html.erb</p>